apiVersion: batch/v1
kind: CronJob
metadata:
  name: bot-monitor
  namespace: {{ .Values.namespace }}
  labels:
    app: bot-monitor
    component: scheduler
spec:
  schedule: "*/5 * * * *"  # Run every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: vexa-bot-manager
          containers:
          - name: bot-monitor
            image: {{ .Values.global.imageRegistry }}/{{ .Values.celery.image.repository }}:{{ .Values.celery.image.tag }}
            imagePullPolicy: {{ .Values.celery.image.pullPolicy }}
            command: ["python", "-c", "from app.tasks.monitoring import monitor_bot_containers; monitor_bot_containers()"]
            env:
              - name: NAMESPACE
                value: {{ .Values.namespace }}
              - name: BOT_IMAGE
                value: {{ .Values.global.imageRegistry }}/{{ .Values.bot.image.repository }}:{{ .Values.bot.image.tag }}
              - name: REDIS_URL
                value: "redis://{{ .Values.redis.name }}-service:{{ .Values.redis.service.port }}/0"
              - name: DB_HOST
                value: {{ .Values.postgres.name }}-service
              - name: DB_PORT
                value: "{{ .Values.postgres.service.port }}"
              - name: DB_NAME
                value: {{ .Values.postgres.database }}
              - name: DB_USER
                value: {{ .Values.postgres.username }}
              - name: DB_PASSWORD
                value: {{ .Values.postgres.password }}
          restartPolicy: OnFailure 