apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.transcriptionService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.transcriptionService.name }}
    component: transcription
spec:
  replicas: {{ .Values.transcriptionService.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.transcriptionService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.transcriptionService.name }}
        component: transcription
    spec:
      containers:
        - name: {{ .Values.transcriptionService.name }}
          image: {{ .Values.global.imageRegistry }}/{{ .Values.transcriptionService.image.repository }}:{{ .Values.transcriptionService.image.tag }}
          imagePullPolicy: {{ .Values.transcriptionService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: BOT_MANAGER_URL
              value: "http://{{ .Values.botManager.name }}-service:{{ .Values.botManager.service.port }}"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: {{ .Values.transcriptionService.resources.requests.cpu }}
              memory: {{ .Values.transcriptionService.resources.requests.memory }}
            limits:
              cpu: {{ .Values.transcriptionService.resources.limits.cpu }}
              memory: {{ .Values.transcriptionService.resources.limits.memory }} 