apiVersion: v1
kind: ServiceAccount
metadata:
  name: vexa-bot-manager
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-manager
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vexa-bot-manager-role-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: vexa-bot-manager
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io 