apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.botManager.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.botManager.name }}
    component: api
spec:
  type: {{ .Values.botManager.service.type }}
  ports:
    - port: {{ .Values.botManager.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.botManager.name }} 