apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.transcriptionService.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.transcriptionService.name }}
    component: transcription
spec:
  type: {{ .Values.transcriptionService.service.type }}
  ports:
    - port: {{ .Values.transcriptionService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.transcriptionService.name }} 