# Default values for vexa Bot Management System
# This is a YAML-formatted file.

# Global configuration
global:
  environment: production
  imageRegistry: gcr.io/your-project

# Namespace
namespace: vexa

# Gateway API configuration
gateway:
  name: gateway
  replicaCount: 2
  image:
    repository: gateway
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8000
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70

# Bot Manager API configuration
botManager:
  name: bot-manager
  replicaCount: 2
  image:
    repository: bot-manager
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 700m
      memory: 1Gi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70

# Transcription Service configuration
transcriptionService:
  name: transcription-service
  replicaCount: 3
  image:
    repository: transcription-service
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      cpu: 400m
      memory: 512Mi
    limits:
      cpu: 800m
      memory: 1Gi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 20
    targetCPUUtilizationPercentage: 60

# Bot configuration
bot:
  image:
    repository: bot
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

# Redis configuration
redis:
  name: redis
  image:
    repository: redis
    tag: 7.0-alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 6379
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  persistence:
    enabled: true
    storageClass: standard
    size: 5Gi

# PostgreSQL configuration
postgres:
  name: postgres
  image:
    repository: postgres
    tag: 15-alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  persistence:
    enabled: true
    storageClass: standard
    size: 10Gi
  database: vexa
  username: postgres
  password: postgres  # In production, use secrets

# Celery worker configuration
celery:
  name: celery-worker
  replicaCount: 2
  image:
    repository: bot-manager  # Reuse the bot-manager image
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70

# Ingress configuration
ingress:
  enabled: true
  className: "gce"
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "vexa-ip"
    kubernetes.io/ingress.allow-http: "true"
  hosts:
    - host: api.example.com
      paths:
        - path: /*
          pathType: ImplementationSpecific
          backend:
            service: gateway
  tls:
    - secretName: api-tls-cert
      hosts:
        - api.example.com 